### ISSUE TITLE
Add possibility to have more instances of AdView in QML

### ISSUE THREAD

**Issue by larpon** [yevgeniy-logachev/QtAdMob#10]
I can't find a way to instantiate more than one of each QML type:

```
AdMobBanner {
...
}

AdMobInterstitial {
...
}
```

Adding a second `AdMobBanner` with a seperate `unitId` results in this exception:

```
W/dalvikvm(19478): threadid=1: thread exiting with uncaught exception (group=0x41f062a0)
E/AndroidRuntime(19478): FATAL EXCEPTION: main
E/AndroidRuntime(19478): java.lang.IllegalStateException: The ad unit ID can only be set once on AdView.
E/AndroidRuntime(19478):    at com.google.android.gms.ads.internal.client.zzae.setAdUnitId(Unknown Source)
E/AndroidRuntime(19478):    at com.google.android.gms.ads.BaseAdView.setAdUnitId(Unknown Source)
E/AndroidRuntime(19478):    at com.google.android.gms.ads.AdView.setAdUnitId(Unknown Source)
E/AndroidRuntime(19478):    at org.dreamdev.QtAdMob.QtAdMobActivity$1.run(QtAdMobActivity.java:50)
E/AndroidRuntime(19478):    at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime(19478):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(19478):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(19478):    at android.app.ActivityThread.main(ActivityThread.java:4867)
E/AndroidRuntime(19478):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19478):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19478):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
E/AndroidRuntime(19478):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
E/AndroidRuntime(19478):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nextgeniuspro** [comment]
I know about this issue, for now status is WIP, I need to reorganize Java sources to support multiple ads simultaneously
