### ISSUE TITLE
App crashes instantly

### ISSUE THREAD

**Issue by OlegRakovich** [yevgeniy-logachev/QtAdMob#23]
I've been trying to include this lib in my project for several days now and I can't get it to work.
I already tried using QtAdMobApp and I have same issue.
When I start application it closes immediately with an error, stack trace is:
```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.dreamdev.QtAdMob, PID: 7617
E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.dreamdev.QtAdMob/org.dreamdev.QtAdMob.QtAdMobActivity}: java.lang.ClassNotFoundException: Didn't find class "org.dreamdev.QtAdMob.QtAdMobActivity" on path: DexPathList[[zip file "/data/app/org.dreamdev.QtAdMob-1/base.apk"],nativeLibraryDirectories=[/data/app/org.dreamdev.QtAdMob-1/lib/arm, /data/app/org.dreamdev.QtAdMob-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2488)
E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5765)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.dreamdev.QtAdMob.QtAdMobActivity" on path: DexPathList[[zip file "/data/app/org.dreamdev.QtAdMob-1/base.apk"],nativeLibraryDirectories=[/data/app/org.dreamdev.QtAdMob-1/lib/arm, /data/app/org.dreamdev.QtAdMob-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1072)
E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2478)
E AndroidRuntime: 	... 9 more
E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: org.dreamdev.QtAdMob.QtAdMobActivity
E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E AndroidRuntime: 		... 12 more
E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```
Please help.

**Comment by OlegRakovich** [comment]
To resolve my issue I had to create folder `platform/android/src` and put `platform/android/org` inside it.
