### ISSUE TITLE
Banner Not Showing QML

### ISSUE THREAD

**Issue by karpinochkin** [yevgeniy-logachev/QtAdMob#28]
I'm creating a banner:
`AdMobInterstitial
{
id: intertitial
visible: true

    Component.onCompleted: {
        intertitial.unitId = "ca-app-pub-xxxxxxxxxxxxxxx/yyyyyyyyyy"
    }

    onClosed: {
        intertitial.unitId = "ca-app-pub-xxxxxxxxxxxxxxx/yyyyyyyyyy"
    }
    onLoaded: {
        console.log("loaded")
    }

    onLoading: {
        console.log("loading")
    }
}`

This is app output:

`D Mobile Client: qml: loading
I hoiceofmajorit: The ClassLoaderContext is a special shared library.
I hoiceofmajorit: The ClassLoaderContext is a special shared library.
I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21800
I DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 21800
D DynamitePackage: Instantiated singleton DynamitePackage.
D DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
D NetworkSecurityConfig: No Network Security Config specified, using platform default
I Ads     : Updating ad debug logging enablement.
I Ads     : Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("2CEA88BC3475902B17D97EF1A9FE33F4") to get test ads on this device.
W hoiceofmajorit: Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
I hoiceofmajorit: The ClassLoaderContext is a special shared library.
I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21800
I DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 21800
I AudioManager: In isSpeakerphoneOn(), calling application: org.comp.choiceofmajority
D AudioManager: getStreamVolume isRestricted mode = 0
D AudioManager: getStreamVolume isRestricted mode = 0
I WebViewFactory: Loading com.android.chrome version 80.0.3987.99 (code 398709932)
I cr_LibraryLoader: Loaded native library version number "80.0.3987.99"
W Ads     : Update ad debug logging enablement as false
W hoiceofmajorit: Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
D EgretLoader: EgretLoader(Context context)
D EgretLoader: The context is not activity
W hoiceofmajorit: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (light greylist, reflection)
W cr_media: Requires BLUETOOTH permission
W VideoCapabilities: Unsupported mime video/divx
W VideoCapabilities: Unsupported mime video/divx311
W VideoCapabilities: Unsupported mime video/divx4
W VideoCapabilities: Unrecognized profile 4 for video/hevc
W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W Utils   : could not parse long range '175-174'
I Ads     : Ad failed to load : 0
I hoiceofmajorit: ProcessProfilingInfo new_methods=952 is saved saved_to_disk=1 resolve_classes_delay=8000
W ConnectionTracker: Exception thrown while unbinding
W ConnectionTracker: java.lang.IllegalArgumentException: Service not registered: lt@2d8d000
W ConnectionTracker: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
W ConnectionTracker: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
W ConnectionTracker: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
W ConnectionTracker: 	at cg.b(:com.google.android.gms.dynamite_measurementdynamite@202465065@20.24.65 (100400-0):1)
W ConnectionTracker: 	at cg.a(:com.google.android.gms.dynamite_measurementdynamite@202465065@20.24.65 (100400-0):6)
W ConnectionTracker: 	at lu.A(:com.google.android.gms.dynamite_measurementdynamite@202465065@20.24.65 (100400-0):10)
W ConnectionTracker: 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@202465065@20.24.65 (100400-0):3)
W ConnectionTracker: 	at dz.run(:com.google.android.gms.dynamite_measurementdynamite@202465065@20.24.65 (100400-0):3)
W ConnectionTracker: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W ConnectionTracker: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W ConnectionTracker: 	at ja.run(:com.google.android.gms.dynamite_measurementdynamite@202465065@20.24.65 (100400-0):6)
W QtThread: type=1400 audit(0.0:3345): avc: denied { ioctl } for path="socket:[640053]" dev="sockfs" ino=640053 ioctlcmd=8b07 scontext=u:r:untrusted_app:s0:c184,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c184,c257,c512,c768 tclass=netlink_route_socket permissive=0
W QtThread: type=1400 audit(0.0:3348): avc: denied { ioctl } for path="socket:[640053]" dev="sockfs" ino=640053 ioctlcmd=8b07 scontext=u:r:untrusted_app:s0:c184,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c184,c257,c512,c768 tclass=netlink_route_socket permissive=0`

Banner not showing. Should I upload a banner before showing? If yes, how? If not, why doesn't it showing?

**Comment by karpinochkin** [comment]
I try run program with test google ads and the program works correctly. Banners are displayed. 

`I Ads : Ad failed to load : 0`

This is what google says

`"It could be that you have only recently created a new Ad Unit ID and requesting for live ads. It could take a few hours for ads to start getting served if that is that case. If you are receiving test ads then your implementation is fine. Just wait a few hours and see if you are able to receive live ads then. If not, can send us your Ad Unit ID for us to look into."`
